[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "testes_pytest"
version = "0.1.0"
description = "Projeto de testes automatizados com Pytest"
authors = [{name = "David"}]
dependencies = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-v"
