[project]
name = "testes_pytest"
version = "0.1.0"
description = "Projeto de testes automatizados com Pytest"
authors = [{ name = "David", email = "gugamartinho@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["src"]

pythonpath = ["src"]
testpaths = ["tests"]
addopts = "-v"
